x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.9.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__DEFAULT_UI_VIEW: graph
    AIRFLOW__PROVIDERS__ODBC__ALLOW_DRIVER_IN_EXTRA: 'True'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs
    - /mnt/e/hisminsa_local:/mnt/e/hisminsa_local
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
           airflow users create --username airflow --password airflow --firstname airflow --lastname airflow --role Admin --email airflow@airflow.com"
    restart: on-failure

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres-db-volume: